name: Build APK

on:
  push:
    branches:
      - main   # يتم تفعيل هذه العملية عندما تقوم برفع تحديثات إلى الفرع "main"

jobs:
  build:
    runs-on: ubuntu-latest   # تحديد نظام التشغيل الذي سيعمل عليه بناء التطبيق

    steps:
      - name: Checkout repository   # الخطوة الأولى هي تحميل الملفات من المستودع
        uses: actions/checkout@v2

      - name: Set up JDK   # إعداد بيئة Java لبناء التطبيق
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build with Gradle   # استخدام أداة Gradle لتجميع التطبيق
        run: ./gradlew assembleDebug   # بناء نسخة Debug من APK

      - name: Upload APK   # رفع ملف APK الناتج
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
